apiVersion: v1
kind: Pod
metadata:
  name: edu-projector-pod
spec:
  containers:
    - name: edu-projector
      image: ghcr.io/as511-devops/edu-projector:pr-2
      ports:
        - containerPort: 8080
