apiVersion: v1
kind: Namespace
metadata:
  name: label-studio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labelstudio-data
  namespace: label-studio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio
  namespace: label-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-studio
  template:
    metadata:
      labels:
        app: label-studio
    spec:
      containers:
        - name: label-studio
          image: heartexlabs/label-studio:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /label-studio/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: labelstudio-data
---
apiVersion: v1
kind: Service
metadata:
  name: label-studio
  namespace: label-studio
spec:
  selector:
    app: label-studio
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort
